### ISSUE TITLE
Bug Report: Checkmarks for Modules Enabled Displayed Incorrectly

### ISSUE THREAD

**Issue by GorgoPrimus** [sdenec/tidy-ui_game-settings#98]
When this module is on, the Manage Module menu shows checkmarks for which module is enabled in the middle of module names instead of in the check boxes - which looks awful and makes it harder to much read the ui.

**Comment by karpana** [comment]
Adding some additional context, as I noticed the same thing on my installation.

This behaviour was not present in v10
it seems to be introduced in v11, even when Tidy UI is the only module running.

**Comment by karpana** [comment]
took a look (in google debug screens) as to what might be causing the issue with the checkmarks moving away from the box.

in the `tidy-ui_game-settings.css` file there is the following code block

```css
#module-management input[type="checkbox"]:checked::after {
  content: "";
  display: block;
  background: url(../img/check-solid.svg) center no-repeat;
  background-size: cover;
  position: absolute;
  width: 16px;
  height: 16px;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

Changing the `left: 50%;` to `left: 2%;` moves the checkbark roughly back to where it needs to be.

this is a far from elegant solution, and probably has more to do with some of the UI changes in v11 than anything else.  But as a quick fix to make this appear less broken, you might find value in this temporary approach.
